### ISSUE TITLE
Support multiple buildslaves

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs-buildbot#14]
The buildbot configuration should be updated to intelligently handle multiple buildslaves per builder.  Specifically we would want the builder to prefer an on-demand t2.micro slave for builds unless the pending builder queue was more than half a dozen deep.  At which point it should be allowed to power up a larger spot instance to speed things up.

This can be done with buildbot adding multiple slaves per builder and providing a custom nextSlave() function which includes the above logic.

**Comment by dinatale2** [comment]
I submitted #19 to optimize how slaves are chosen based on their state. Not quite what you are looking for to satisfy this I think. Figured I'd mention it though.

**Comment by behlendorf** [comment]
There's certainly room for further improvement but this is definitely a step in the right direction.
