### ISSUE TITLE
keepalive_interval never used when making a test slave

### ISSUE THREAD

**Issue by dinatale2** [zfsonlinux/zfs-buildbot#17]
mkEC2TestSlave passes keepalive_interval=60 to mkEC2UserDataSlave. mkEC2UserDataSlave does not handle keepalive_interval. Solution is simple, add handling for keepalive_interval in mkEC2UserDataSlave. Only question is, what's an appropriate default value for keepalive_interval?

**Comment by behlendorf** [comment]
Internally buildbot sets the default to 3600 seconds, which I think might be a bit long but best to stick with the existing defaults.  It will be interesting to see if fixing this helps reap crashes VMs faster as expected.

**Comment by dinatale2** [comment]
Actually.... I'm looking at the EC2LatentBuildSlave class, and it appears that it doesn't actually accept a keepalive_interval. It also doesn't pass any value for it to its base class (AbstractLatentBuildSlave) on initialization. This may actually require a patch to BuildBot itself to get working.

**Comment by behlendorf** [comment]
That's alright if it solves the issue.  We can feed it back upstream.
