### ISSUE TITLE
not specifying "Requires-spl:" fails to clone spl-0.7-release branch

### ISSUE THREAD

**Issue by gyakovlev** [zfsonlinux/zfs-buildbot#170]
somehow stray`"` gets appended to git clone branch parameter

```
 watching logfiles {}
 argv: ['git', 'clone', '--branch', 'spl-0.7-release"', 'https://github.com/zfsonlinux/spl.git', '.']
 using PTY: False
Cloning into '.'...
fatal: Remote branch spl-0.7-release" not found in upstream origin
```

check build logs from https://github.com/zfsonlinux/zfs/pull/8227 

and a workaround by adding `Requires-spl: spl-0.7-release`
https://github.com/zfsonlinux/zfs/pull/8256

not sure how this `"` gets there and what leaks it.

**Comment by behlendorf** [comment]
I'm not sure about the leak, but `Requires-spl: spl-0.7-release` was the intended interface for this purpose.  Given that the SPL has been integrated with ZFS I don't think this is something we'll want to invest the time in investigating.  Sorry, we didn't get a chance to look at this but thanks for letting us know.
