### ISSUE TITLE
Update the Instance Type to M5.Large

### ISSUE THREAD

**Issue by Tilton53** [zfsonlinux/zfs-buildbot#174]
You're stilling using the m3.large instance type which is $.14 an hour standard and 2vCPU,7.5GB-RAM. You may be able to get better and cheaper performance by migrating to the newer M5.Large instances which are $0.096 an hour and 2vCPU/8GB-RAM.

**Comment by behlendorf** [comment]
Thanks for the suggestion, we'll look in to it.

**Comment by behlendorf** [comment]
The test instance types have been updated.
