### ISSUE TITLE
List of public push webhooks

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs-buildbot#24]
It would be nice to have a list of the public (if any) PUSH web hooks in the ZoL repos.

I'm considering setting up a Jenkins auto builder at home, but I need (would like) the URLs to subscribe to.

**Comment by behlendorf** [comment]
All of Github's webhooks are private as described in the [documentation](https://developer.github.com/webhooks/).  However, I'm find with registering one for you if you're interesting in setting up you own infrastructure.  All that's required is knowing which webhooks you want to receive and where to send them.

**Comment by FransUrbo** [comment]
I see, thanx! I thought there was public ones as well (I've just started looking into this :). I'll let you know when I'm done in my end, thanx.

**Comment by behlendorf** [comment]
Please keep in mind the existing infrastructure in the back of your mind too.  Maybe some of what you're working on could be folded in to improve that automated testing.
