### ISSUE TITLE
Introduce a rebase check to the STYLE builder

### ISSUE THREAD

**Issue by dinatale2** [zfsonlinux/zfs-buildbot#35]
As pull requests become older, it is highly likely that bug fixes have been performed. Some of these bug fixes/improvements are either fixes to issues found in the test suite or changes that may impact the test suite (i.e. disabled/enabled tests). To combat this, we can introduce a check in the STYLE builder which can try and determine how "stale" a pull request is.

**Comment by dinatale2** [comment]
We can also use this issue to brainstorm other similar and smaller tasks.

**Comment by behlendorf** [comment]
In practice, Github's conflicts sections has does a reasonable job notifying us when a PR is "stale".
