### ISSUE TITLE
priority of building

### ISSUE THREAD

**Issue by inkdot7** [zfsonlinux/zfs-buildbot#40]
I've noticed that the build system build commits in the order that they were pushed to the pull requests.  It also seems that all commits in a pull request are rebuilt, even if only a new commit is pushed at the end.

If possible, it would be nice to:
- First build all 'final' commits, i.e. the ones where currently the TEST builds are performed.
  Then single-commit pull requests are not so easily stalled by multi-commit requests.
- Prefer to build commits that have most other successfully built commits.
  Then code that fails style check and later fast builds will not hold the slower builders.

**Comment by dinatale2** [comment]
@inkdot7 Thank you for opening this issue. These are all valid points. Below are my thoughts on each.

- Building all the 'final' commits may be doable. When creating a buildbot builder, it is possible to specify a function to choose the next build. Perhaps, that may be worth looking into?
- For optimizing which commits get built, we could do require that commits pass the STYLE builder before triggering other. We could create a "fast TEST" builder which can run a subset of the test suite and once that passes, we can then trigger the TEST builders.
- For the only building new commits, this is tracked by commit hash if I am not mistaken. I believe github issues a synchronize event via it's webhook. I believe it contains only the commit hashes that changed, but I could be wrong about that.

Would you be interested in attempting to tackle the above?

**Comment by inkdot7** [comment]
@dinatale2 Thanks for the quick response.  I looked around in the code a bit:

- In `class CustomGitHubEventHandler` of `master/master.cfg`, there is `commits_cur` which gives the part number of a commit.  If adding this to the `change` dictionary makes it visible(?) to a `nextBuild` method of `class ZFSBuilderConfig` in `master/buildslaves.py` then reordering builds would be easy.  If the value is also set to `0` for `commits_cur == commits_num`, then it would be straight-forward for `nextBuild`: choose the first request with the lowest number: final commits gets built before others, and others are built such that the ends of long commit chains have to wait for shorter chains.

  I could try to make a patch/pull request.  But it would be untested, as I've no experience setting up a buildbot system.  Useful?

- Introducing a fast TEST would make the test builds finish later, which is not so nice.  As those have many builders, I've not felt any problems there.  Also, as the tests sometimes give spurious failures, it would not be nice if that prevents the other tests from running.

- That rebased commit chains are fully rebuilt makes sense.  It looks like extra rebuilds of unchanged commits when just one new is added is due to `class CustomGitHubEventHandler`, which adds all commits as changes when it gets told about a new update.

  I do not know if the buildbot system tries to remove duplicate changes, but that may be thwarted by the fact that `part %d/%d` is added to each change comment, and thus change when more commits are added to a chain.

  Otherwise, a global dictionary of commits that have been added as changes would be needed to avoid these rebuilds.  But the re-prioritisation above is probably enough.

**Comment by inkdot7** [comment]
There is also some `mergeRequests` or `collapseRequests` buildbot functionality.  Perhaps this can be used to remove duplicate builds of the same commit.

**Comment by dinatale2** [comment]
I don't think `mergeRequests` or `collapseRequests` are what you want. I think you had the right idea with `nextBuild`. Go ahead and make a pull request for a `nextBuild` function to do the re-prioritisation as you described. I have a small development environment setup to test proposed changes and can let you know if your proposed change will work or not.

I don't think the global dictionary of commits is a bad idea. I want to determine what information comes from a github synchronization event before we make that change though.

**Comment by dinatale2** [comment]
Ok, I think I was probably wrong on the pull request event synchronize action. I think the commit url will always provide the complete list of commits. I'm not opposed to introducing the dictionary to keep track of the hashes. I highly recommend you look into how to limit the amount of memory that dictionary may take up though since the build master is a long living instance.

**Comment by inkdot7** [comment]
Pull request is there, but with it written semi-blind, expect the worst...

Regarding duplicates: [https://developer.github.com/v3/activity/events/types/#pushevent](https://developer.github.com/v3/activity/events/types/#pushevent) makes me suspect that there could be an `distinct` member of each commit, that may be of use.

Otherwise, a dictionary might be more clear in what it does.  One could keep a list of e.g. the 100 last unique commit sha that have been propagated through `CustomGitHubEventHandler`.  Then it will not grow too large.  With the current turn-around in the buildbots, that should be plenty.  The main purpose is to prevent back-to-back rebuilds when additional fix-up commits are pushed. Each time `handle_pull_request` is invoked, a local dictionary for quick lookup could be made from the list.
