### ISSUE TITLE
Avoid rebuilding previously built commits when a pull request is refreshed.

### ISSUE THREAD

**Issue by dinatale2** [zfsonlinux/zfs-buildbot#43]
When a pull request is refreshed, the ZFS buildbot may rebuild commits that have already been built and haven't changed. It appears that the pull request event w/ synchronize action points us to a full list of commits. So to avoid duplicates, we would need to add some form of mechanism to the buildbot to keep track of what has been recently built.

We began discussing this in #40. Creating an issue so we don't lose track of it.

Suggestions from @inkdot7:

> Regarding duplicates: https://developer.github.com/v3/activity/events/types/#pushevent makes me suspect that there could be an distinct member of each commit, that may be of use.
>
> Otherwise, a dictionary might be more clear in what it does. One could keep a list of e.g. the 100 last unique commit sha that have been propagated through CustomGitHubEventHandler. Then it will not grow too large. With the current turn-around in the buildbots, that should be plenty. The main purpose is to prevent back-to-back rebuilds when additional fix-up commits are pushed. Each time handle_pull_request is invoked, a local dictionary for quick lookup could be made from the list.

**Comment by behlendorf** [comment]
Closing.  In practice this hasn't been an issue.
