### ISSUE TITLE
Automate OpenZFS patch porting

### ISSUE THREAD

**Issue by dinatale2** [zfsonlinux/zfs-buildbot#50]
We recently discovered that it is possible to cherry-pick patches directly from the OpenZFS tree. Git will automatically attempt to find the right file to apply a hunk to if it is given enough time to process a change.

To allow git the time to search, you need the following in your git config
```
[merge]
    renameLimit = 999999
```
Now, in order to cherry-pick, clone your fork of zfs and add both zfsonlinux/zfs and openzfs/openzfs as remotes. Perform a `git fetch --all`. Now you can perform a `git cherry-pick <OpenZFS commit>` to port patches to ZoL.

It would be nice to have a script that would attempt to perform the above process automatically given an OpenZFS commit.

**Comment by dinatale2** [comment]
@gmelikov you might be interested in this

**Comment by gmelikov** [comment]
Thanks, i thought about that scenario too. I'll try to make a script for it.

**Comment by gmelikov** [comment]
@dinatale2 thanks for initial method!
I alreadt made a prototype, it works smoothly. I'll make a PR after massive test.

**Comment by gmelikov** [comment]
Most of my last PRs are made by script, but unfourtunately these are all that can be merged automatically for now.

One major problem - new files merge with OpenZFS file structure, example - https://github.com/gmelikov/zfs/commit/df3e48b064a553fa0fc9178d2a71fc57008edb0c

I'll beautify the script and make a PR later.

**Comment by dinatale2** [comment]
This was taken care of in #51. Thanks @gmelikov!
