### ISSUE TITLE
Debian 8 x86_64 (TEST) reports bc not found 

### ISSUE THREAD

**Issue by ofaaland** [zfsonlinux/zfs-buildbot#8]
build step 13, xfstests failed.  stdio output shows that it is failing to find 'bc' (the math program) when checking its environment, before running any actual tests.

```
+ sudo -E ./check -zfs -x dio -x sendfile -x user
bc not found
+ RESULT=1
+ exit 1
```

This string appears in the xfstests-zfs code, in common.config:
```
130 export SED_PROG="`set_prog_path sed`"
131 [ "$SED_PROG" = "" ] && _fatal "sed not found"
132
133 export BC_PROG="`set_prog_path bc`"
134 [ "$BC_PROG" = "" ] && _fatal "bc not found"
135
136 export PS_ALL_FLAGS="-ef"
137
```

**Comment by ofaaland** [comment]
Looks like the debian package is called 'bc'

**Comment by ofaaland** [comment]
Submitted PR https://github.com/zfsonlinux/zfs-buildbot/pull/9

**Comment by behlendorf** [comment]
Merged as:

9ddb239 Debian 8 required bc for xfstests
